set_property PACKAGE_PIN A15 [get_ports FPGA_RESET_N_PIN]
set_property PACKAGE_PIN A13 [get_ports I2C_OR_SPI_POUT]
set_property PACKAGE_PIN AF22 [get_ports OSC_CLK_40M_PIN]
set_property PACKAGE_PIN B12 [get_ports SCLK_POUT]
set_property PACKAGE_PIN A11 [get_ports SI5345_MOSI_POUT]
set_property PACKAGE_PIN A12 [get_ports SI5345_MISO_PIN]
set_property PACKAGE_PIN B13 [get_ports SPI_CS_N_POUT]
set_property IOSTANDARD LVCMOS33 [get_ports FPGA_RESET_N_PIN]

set_property IOSTANDARD LVCMOS33 [get_ports I2C_OR_SPI_POUT]
set_property IOSTANDARD LVCMOS33 [get_ports OSC_CLK_40M_PIN]
set_property IOSTANDARD LVCMOS33 [get_ports SCLK_POUT]
set_property IOSTANDARD LVCMOS33 [get_ports SI5345_MISO_PIN]
set_property IOSTANDARD LVCMOS33 [get_ports SI5345_MOSI_POUT]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS_N_POUT]

create_clock -period 25.000 -name OSC_CLK_40M_PIN -waveform {0.000 12.500} [get_ports OSC_CLK_40M_PIN]

set_property IOSTANDARD LVCMOS33 [get_ports {IN_SEL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {IN_SEL[0]}]
set_property PACKAGE_PIN F15 [get_ports {IN_SEL[0]}]
set_property PACKAGE_PIN F13 [get_ports {IN_SEL[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports SI5345_RST_N_POUT]
set_property PACKAGE_PIN E14 [get_ports SI5345_RST_N_POUT]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets top_clk40m]
